-- Migration 004: Research Log (Module 3)
-- TIMESTAMP: 2026-05-09 15:42 UTC
-- Creates research_sessions and session_sources tables.
-- Run AFTER 001-create-tables.sql, 002-add-res-checklist.sql, 003-add-documents.sql.

-- research_sessions: one record per research session
create table if not exists research_sessions (
  id               uuid primary key default gen_random_uuid(),
  session_date     date not null,
  title            text not null,              -- brief session title: "1920 census search for Jacob Singer"
  goal             text not null,              -- researcher's stated goal for this session
  person_id        uuid references persons(id) on delete set null,
  -- research_plan_id column will be added by Module 2 migration when Research Plan Builder is built
  finds            text,                        -- what was found (narrative)
  negatives        text,                        -- what was NOT found (negative evidence -- GPS requires this)
  follow_up        text,                        -- follow-up actions generated by this session
  notes            text,                        -- freeform notes; input for AI abstraction
  status           text not null default 'draft'
                   check (status in ('draft','complete')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- session_sources: which sources were consulted during a session
-- Tracks both sources that yielded results AND those that yielded nothing.
-- Under GPS, a source that yields nothing is still evidence and must be documented.
create table if not exists session_sources (
  id                  uuid primary key default gen_random_uuid(),
  session_id          uuid not null references research_sessions(id) on delete cascade,
  source_id           uuid references sources(id) on delete set null,
  source_label        text not null,           -- denormalized label in case source record is later deleted
  yielded_results     boolean not null default false,
  result_summary      text,                    -- brief note on what was found or not found
  display_order       int not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- RLS: single-user application; authenticated user has full access
alter table research_sessions enable row level security;
alter table session_sources    enable row level security;

create policy "research_sessions_select" on research_sessions
  for select using (auth.role() = 'authenticated');
create policy "research_sessions_insert" on research_sessions
  for insert with check (auth.role() = 'authenticated');
create policy "research_sessions_update" on research_sessions
  for update using (auth.role() = 'authenticated');
create policy "research_sessions_delete" on research_sessions
  for delete using (auth.role() = 'authenticated');

create policy "session_sources_select" on session_sources
  for select using (auth.role() = 'authenticated');
create policy "session_sources_insert" on session_sources
  for insert with check (auth.role() = 'authenticated');
create policy "session_sources_update" on session_sources
  for update using (auth.role() = 'authenticated');
create policy "session_sources_delete" on session_sources
  for delete using (auth.role() = 'authenticated');
