'use client'

import { useState, useEffect, useCallback } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import type { ResearchSession, SessionSource, Source } from '@/types'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type SectionKey = 'goal' | 'finds' | 'negatives' | 'follow_up' | 'notes'

const SECTION_LABELS: Record<SectionKey, { label: string; description: string }> = {
  goal:      { label: 'Research Goal',     description: 'The specific question this session was trying to answer.' },
  finds:     { label: 'Finds',             description: 'What was discovered. Positive information yielded by this session.' },
  negatives: { label: 'Negative Results',  description: 'Sources searched that yielded nothing. Under GPS, this is evidence and must be documented.' },
  follow_up: { label: 'Follow-Up Actions', description: 'Actions generated by this session. What remains unresolved or should be searched next.' },
  notes:     { label: 'Session Notes',     description: 'Freeform notes or raw research conversation. Used as input for AI abstraction.' },
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

export default function ResearchSessionDetailPage() {
  const { id } = useParams<{ id: string }>()

  const [session,        setSession]        = useState<ResearchSession | null>(null)
  const [sources,        setSources]        = useState<SessionSource[]>([])
  const [availSources,   setAvailSources]   = useState<Source[]>([])
  const [loading,        setLoading]        = useState(true)
  const [error,          setError]          = useState<string | null>(null)
  const [saving,         setSaving]         = useState<SectionKey | null>(null)
  const [abstracting,    setAbstracting]    = useState(false)
  const [abstractError,  setAbstractError]  = useState<string | null>(null)
  const [editValues,     setEditValues]     = useState<Partial<Record<SectionKey, string>>>({})
  const [editingSection, setEditingSection] = useState<SectionKey | null>(null)

  // Source panel state
  const [showAddSource,  setShowAddSource]  = useState(false)
  const [sourceLabel,    setSourceLabel]    = useState('')
  const [linkedSourceId, setLinkedSourceId] = useState('')
  const [yielded,        setYielded]        = useState(false)
  const [resultSummary,  setResultSummary]  = useState('')
  const [addingSource,   setAddingSource]   = useState(false)
  const [addSourceError, setAddSourceError] = useState<string | null>(null)

  const load = useCallback(async () => {
    try {
      const [sRes, srcRes] = await Promise.all([
        fetch(`/api/research-log/${id}`),
        fetch('/api/citation-builder'),
      ])
      const sData   = await sRes.json()
      const srcData = await srcRes.json()
      if (!sRes.ok) throw new Error(sData.error ?? 'Session not found')
      setSession(sData.session)
      setSources(sData.session.session_sources ?? [])
      setAvailSources(srcData.sources ?? [])
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }, [id])

  useEffect(() => { load() }, [load])

  // ---------------------------------------------------------------------------
  // Inline edit helpers
  // ---------------------------------------------------------------------------

  function startEdit(key: SectionKey) {
    setEditingSection(key)
    setEditValues(prev => ({ ...prev, [key]: session?.[key] ?? '' }))
  }

  async function saveSection(key: SectionKey) {
    if (!session) return
    setSaving(key)
    try {
      const res  = await fetch(`/api/research-log/${id}`, {
        method:  'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ [key]: editValues[key]?.trim() || null }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setSession(data.session)
      setEditingSection(null)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Save failed')
    } finally {
      setSaving(null)
    }
  }

  async function markComplete() {
    if (!session) return
    const newStatus = session.status === 'complete' ? 'draft' : 'complete'
    const res  = await fetch(`/api/research-log/${id}`, {
      method:  'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ status: newStatus }),
    })
    const data = await res.json()
    if (res.ok) setSession(data.session)
  }

  // ---------------------------------------------------------------------------
  // AI abstraction
  // ---------------------------------------------------------------------------

  async function handleAbstract() {
    setAbstracting(true)
    setAbstractError(null)
    try {
      const res  = await fetch(`/api/research-log/${id}/abstract`, { method: 'POST' })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setSession(data.session)
    } catch (err) {
      setAbstractError(err instanceof Error ? err.message : 'Abstraction failed')
    } finally {
      setAbstracting(false)
    }
  }

  // ---------------------------------------------------------------------------
  // Session sources
  // ---------------------------------------------------------------------------

  async function handleAddSource() {
    if (!sourceLabel.trim()) { setAddSourceError('Source label is required.'); return }
    setAddingSource(true)
    setAddSourceError(null)
    try {
      const res  = await fetch(`/api/research-log/${id}/session-sources`, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({
          source_id:      linkedSourceId || null,
          source_label:   sourceLabel.trim(),
          yielded_results: yielded,
          result_summary: resultSummary.trim() || null,
          display_order:  sources.length,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setSources(prev => [...prev, data.session_source])
      setSourceLabel('')
      setLinkedSourceId('')
      setYielded(false)
      setResultSummary('')
      setShowAddSource(false)
    } catch (err) {
      setAddSourceError(err instanceof Error ? err.message : 'Failed to add source')
    } finally {
      setAddingSource(false)
    }
  }

  async function handleToggleYielded(src: SessionSource) {
    const res  = await fetch(`/api/research-log/${id}/session-sources/${src.id}`, {
      method:  'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ yielded_results: !src.yielded_results }),
    })
    const data = await res.json()
    if (res.ok) setSources(prev => prev.map(s => s.id === src.id ? data.session_source : s))
  }

  async function handleDeleteSource(srcId: string) {
    const res = await fetch(`/api/research-log/${id}/session-sources/${srcId}`, { method: 'DELETE' })
    if (res.ok) setSources(prev => prev.filter(s => s.id !== srcId))
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  if (loading) {
    return (
      <div className="min-h-screen bg-[var(--color-bg)] flex items-center justify-center">
        <p className="text-sm text-[var(--color-text-muted)]">Loading session...</p>
      </div>
    )
  }

  if (error || !session) {
    return (
      <div className="min-h-screen bg-[var(--color-bg)] flex items-center justify-center">
        <div className="text-center">
          <p className="text-sm text-red-400 mb-4">{error ?? 'Session not found'}</p>
          <Link href="/research-log" className="text-xs text-[var(--color-gold)] hover:underline">Back to Research Log</Link>
        </div>
      </div>
    )
  }

  const sectionKeys: SectionKey[] = ['goal', 'finds', 'negatives', 'follow_up', 'notes']

  return (
    <div className="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)]">
      <div className="max-w-4xl mx-auto px-6 py-10">

        {/* Header */}
        <div className="mb-8">
          <Link href="/research-log" className="text-xs text-[var(--color-text-muted)] hover:text-[var(--color-gold)] block mb-3">
            &larr; Research Log
          </Link>
          <div className="flex items-start justify-between gap-4">
            <div>
              <h1 className="font-display text-3xl text-[var(--color-gold)] mb-1">{session.title}</h1>
              <p className="text-sm text-[var(--color-text-muted)] font-mono">
                {new Date(session.session_date + 'T00:00:00').toLocaleDateString(undefined, {
                  weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
                })}
                {session.person && ` · ${session.person.display_name}`}
              </p>
            </div>
            <button
              onClick={markComplete}
              className={`shrink-0 px-3 py-1.5 text-xs font-mono border rounded transition-colors ${
                session.status === 'complete'
                  ? 'bg-green-50 border-green-200 text-green-700 hover:bg-green-100'
                  : 'bg-[var(--color-surface)] border-[var(--color-border)] text-[var(--color-text-muted)] hover:border-[var(--color-gold)]'
              }`}
            >
              {session.status === 'complete' ? 'Complete' : 'Mark Complete'}
            </button>
          </div>
        </div>

        {/* AI Abstraction panel */}
        <div className="mb-8 p-4 bg-[var(--color-surface)] border border-[var(--color-border)] rounded">
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-[var(--color-text)] mb-1">AI Session Abstractor</p>
              <p className="text-xs text-[var(--color-text-muted)]">
                Add freeform notes below, then run the abstractor to extract structured finds,
                negative results, and follow-up actions. Anti-fabrication enforced -- only what is in your notes.
              </p>
            </div>
            <button
              onClick={handleAbstract}
              disabled={abstracting || !session.notes?.trim()}
              className="shrink-0 px-3 py-1.5 bg-[var(--color-gold)] text-[var(--color-bg)] text-xs font-semibold rounded hover:opacity-90 transition-opacity disabled:opacity-40"
            >
              {abstracting ? 'Abstracting...' : 'Run Abstractor'}
            </button>
          </div>
          {abstractError && (
            <p className="text-xs text-red-400 mt-3">{abstractError}</p>
          )}
        </div>

        {/* Section fields */}
        <div className="space-y-6 mb-10">
          {sectionKeys.map(key => {
            const meta      = SECTION_LABELS[key]
            const value     = session[key] ?? ''
            const isEditing = editingSection === key
            const isSaving  = saving === key

            return (
              <div key={key} className="p-5 bg-[var(--color-surface)] border border-[var(--color-border)] rounded">
                <div className="flex items-start justify-between gap-4 mb-3">
                  <div>
                    <p className="text-xs font-mono text-[var(--color-text-muted)] uppercase tracking-widest mb-0.5">{meta.label}</p>
                    <p className="text-xs text-[var(--color-text-muted)]">{meta.description}</p>
                  </div>
                  {!isEditing && (
                    <button
                      onClick={() => startEdit(key)}
                      className="shrink-0 text-xs text-[var(--color-text-muted)] hover:text-[var(--color-gold)] font-mono transition-colors"
                    >
                      Edit
                    </button>
                  )}
                </div>

                {isEditing ? (
                  <div>
                    <textarea
                      value={editValues[key] ?? ''}
                      onChange={e => setEditValues(prev => ({ ...prev, [key]: e.target.value }))}
                      rows={6}
                      className="w-full px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm text-[var(--color-text)] focus:outline-none focus:border-[var(--color-gold)] resize-y font-mono"
                    />
                    <div className="flex gap-2 mt-2">
                      <button
                        onClick={() => saveSection(key)}
                        disabled={isSaving}
                        className="px-3 py-1.5 bg-[var(--color-gold)] text-[var(--color-bg)] text-xs font-semibold rounded hover:opacity-90 disabled:opacity-50"
                      >
                        {isSaving ? 'Saving...' : 'Save'}
                      </button>
                      <button
                        onClick={() => setEditingSection(null)}
                        className="px-3 py-1.5 text-xs text-[var(--color-text-muted)] hover:text-[var(--color-text)] border border-[var(--color-border)] rounded"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="min-h-[3rem]">
                    {value ? (
                      <p className="text-sm text-[var(--color-text)] whitespace-pre-wrap">{value}</p>
                    ) : (
                      <p className="text-xs text-[var(--color-text-muted)] italic">
                        {key === 'notes' ? 'No notes yet. Click Edit to add freeform notes or paste a research conversation.' :
                         key === 'finds' ? 'No finds recorded yet.' :
                         key === 'negatives' ? 'No negative results recorded yet.' :
                         key === 'follow_up' ? 'No follow-up actions recorded yet.' :
                         'Not set.'}
                      </p>
                    )}
                  </div>
                )}
              </div>
            )
          })}
        </div>

        {/* Sources searched */}
        <div className="mb-10">
          <div className="flex items-center justify-between mb-4">
            <div>
              <p className="text-xs font-mono text-[var(--color-text-muted)] uppercase tracking-widest mb-0.5">Sources Searched</p>
              <p className="text-xs text-[var(--color-text-muted)]">
                Every source consulted this session -- including those that yielded nothing.
                Negative searches are GPS evidence.
              </p>
            </div>
            <button
              onClick={() => setShowAddSource(v => !v)}
              className="px-3 py-1.5 bg-[var(--color-gold)] text-[var(--color-bg)] text-xs font-semibold rounded hover:opacity-90 transition-opacity"
            >
              + Add Source
            </button>
          </div>

          {/* Add source form */}
          {showAddSource && (
            <div className="mb-4 p-4 bg-[var(--color-surface)] border border-[var(--color-border)] rounded space-y-3">
              {addSourceError && (
                <p className="text-xs text-red-400">{addSourceError}</p>
              )}

              {/* Link to existing Citation Builder source */}
              {availSources.length > 0 && (
                <div>
                  <label className="block text-xs font-mono text-[var(--color-text-muted)] uppercase tracking-widest mb-1.5">
                    Link to Citation Builder Source
                  </label>
                  <select
                    value={linkedSourceId}
                    onChange={e => {
                      setLinkedSourceId(e.target.value)
                      if (e.target.value) {
                        const src = availSources.find(s => s.id === e.target.value)
                        if (src) setSourceLabel(src.label)
                      }
                    }}
                    className="w-full px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm text-[var(--color-text)] focus:outline-none focus:border-[var(--color-gold)]"
                  >
                    <option value="">-- Unlinked / new source --</option>
                    {availSources.map(s => (
                      <option key={s.id} value={s.id}>{s.label}</option>
                    ))}
                  </select>
                </div>
              )}

              <div>
                <label className="block text-xs font-mono text-[var(--color-text-muted)] uppercase tracking-widest mb-1.5">
                  Source Label <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={sourceLabel}
                  onChange={e => setSourceLabel(e.target.value)}
                  placeholder="e.g. 1920 US Census, New York, Kings County"
                  className="w-full px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm text-[var(--color-text)] focus:outline-none focus:border-[var(--color-gold)] placeholder:text-[var(--color-text-muted)]"
                />
              </div>

              <div className="flex items-center gap-3">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={yielded}
                    onChange={e => setYielded(e.target.checked)}
                    className="accent-[var(--color-gold)]"
                  />
                  <span className="text-sm text-[var(--color-text)]">This source yielded results</span>
                </label>
              </div>

              <div>
                <label className="block text-xs font-mono text-[var(--color-text-muted)] uppercase tracking-widest mb-1.5">
                  Result Summary
                </label>
                <textarea
                  value={resultSummary}
                  onChange={e => setResultSummary(e.target.value)}
                  placeholder={yielded ? 'What was found in this source?' : 'Why did this source yield nothing? What was absent?'}
                  rows={2}
                  className="w-full px-3 py-2 bg-[var(--color-bg)] border border-[var(--color-border)] rounded text-sm text-[var(--color-text)] focus:outline-none focus:border-[var(--color-gold)] placeholder:text-[var(--color-text-muted)] resize-y"
                />
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handleAddSource}
                  disabled={addingSource}
                  className="px-3 py-1.5 bg-[var(--color-gold)] text-[var(--color-bg)] text-xs font-semibold rounded hover:opacity-90 disabled:opacity-50"
                >
                  {addingSource ? 'Adding...' : 'Add Source'}
                </button>
                <button
                  onClick={() => { setShowAddSource(false); setAddSourceError(null) }}
                  className="px-3 py-1.5 text-xs text-[var(--color-text-muted)] hover:text-[var(--color-text)] border border-[var(--color-border)] rounded"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}

          {/* Source list */}
          {sources.length === 0 ? (
            <div className="p-5 bg-[var(--color-surface)] border border-[var(--color-border)] rounded">
              <p className="text-xs text-[var(--color-text-muted)] italic">
                No sources logged for this session yet. Add every source you consulted -- including those that yielded nothing.
              </p>
            </div>
          ) : (
            <div className="space-y-2">
              {sources
                .sort((a, b) => a.display_order - b.display_order)
                .map(src => (
                  <div
                    key={src.id}
                    className="flex items-start gap-3 p-4 bg-[var(--color-surface)] border border-[var(--color-border)] rounded"
                  >
                    {/* Yielded toggle */}
                    <button
                      onClick={() => handleToggleYielded(src)}
                      title={src.yielded_results ? 'Yielded results -- click to mark negative' : 'No results -- click to mark positive'}
                      className={`mt-0.5 shrink-0 w-4 h-4 rounded-full border-2 transition-colors ${
                        src.yielded_results
                          ? 'bg-green-500 border-green-500'
                          : 'bg-transparent border-[var(--color-border)]'
                      }`}
                    />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-semibold text-[var(--color-text)] mb-0.5">{src.source_label}</p>
                      {src.result_summary && (
                        <p className="text-xs text-[var(--color-text-muted)]">{src.result_summary}</p>
                      )}
                      <div className="flex items-center gap-2 mt-1.5">
                        <span className={`text-xs font-mono ${
                          src.yielded_results ? 'text-green-600' : 'text-[var(--color-text-muted)]'
                        }`}>
                          {src.yielded_results ? 'Results found' : 'No results (negative evidence)'}
                        </span>
                        {src.source && (
                          <span className="text-xs text-[var(--color-text-muted)]">&#183; Linked to Citation Builder</span>
                        )}
                      </div>
                    </div>
                    <button
                      onClick={() => handleDeleteSource(src.id)}
                      className="shrink-0 text-xs text-[var(--color-text-muted)] hover:text-red-400 font-mono transition-colors"
                    >
                      Remove
                    </button>
                  </div>
                ))}
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
